// MEDIA ACTION

export const LOADING_MEDIA_START = "LOADING_MEDIA_START";

export const LOADING_MEDIA_ALBUM = "LOADING_MEDIA_ALBUM";
export const LOADING_MEDIA_MUSIC = "LOADING_MEDIA_MUSIC";
export const LOADING_MEDIA_ARTIST = "LOADING_MEDIA_ARTIST";
export const LOADING_MEDIA_PLAYLIST = "LOADING_MEDIA_PLAYLIST";
export const LOADING_MEDIA_ERROR = "LOADING_MEDIA_ERROR";

export const LOADING_MEDIA_FINISHED = "LOADING_MEDIA_FINISHED";

// PLAYLIST ACTION

export const LOADING_PLAYLIST_START = "LOADING_PLAYLIST_START";

export const LOADING_PLAYLIST = "LOADING_PLAYLIST";
export const SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST";
export const REPEAT_PLAYLIST = "REPEAT_PLAYLIST";
export const TOGGLE_PLAYLIST = "TOGGLE_PLAYLIST";
export const NEXT_PLAYLIST = "NEXT_PLAYLIST";
export const PREV_PLAYLIST = "PREV_PLAYLIST";
export const PROGRESS = "PROGRESS";
export const SEEKTO = "SEEKTO";
export const STATE = "STATE";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const NEW_PLATLIST = "NEW_PLATLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const LOADING_PLAYLIST_FINISHED = "LOADING_PLAYLIST_FINISHED ";
